import {
  Wrench,
  FileText,
  ShieldCheck,
  LockKeyhole,
  CreditCard,
  Printer,
  Smartphone,
  Zap,
  Battery,
  Volume2,
  ScanLine,
  IdCard,
  Landmark,
  ClipboardList,
  Upload,
  Settings,
} from "lucide-react";

export const shop = {
  name: "Shiv Shakti Cellcome",
  tagline: "Mobile Repair • Accessories • Online Services",
  shortTagline: "Your local mobile & digital service store",
  phone: "+91 7697233783, 9770675711",
  whatsapp: "917697233783",
  email: "shiv.shakti.celcome.gov@gmail.com",
  address: "Surpura In Front Hanuman Temple",
  hours: "Mon–Sat • 9:00 AM – 7:00 PM",
  rating: 4.8,
  reviewCount: 127,
};

export const team = [
  {
    id: "team1",
    name: "Anoop Singh Bhadouriya",
    role: "Repairing & Accessories",
    description: "Mobile repairing and accessories.",
    icon: Wrench,
  },
  {
    id: "team2",
    name: "Vikash Singh Bhadouriya",
    role: "Online & Digital Services",
    description: "Online forms and digital services.",
    icon: FileText,
  },
];

export const services = [
  {
    id: "s1",
    category: "Repairing",
    name: "Mobile Repairing",
    desc: "Screen, battery, charging, software and hardware diagnosis.",
    managedBy: "Anoop",
    icon: Wrench,
    badge: "Popular",
    featured: true,
    available: true,
    tags: ["Display", "Battery", "Charging", "Software"],
  },
  {
    id: "s2",
    category: "Repairing",
    name: "Display & Touch Repair",
    desc: "Display, touch and screen-related repair assistance.",
    managedBy: "Anoop",
    icon: Smartphone,
    badge: "Repair",
    featured: true,
    available: true,
    tags: ["Display", "Touch", "Screen"],
  },
  {
    id: "s3",
    category: "Repairing",
    name: "Battery Replacement",
    desc: "Battery diagnosis and replacement for supported models.",
    managedBy: "Anoop",
    icon: Battery,
    badge: "Repair",
    featured: false,
    available: true,
    tags: ["Battery", "Replacement"],
  },
  {
    id: "s4",
    category: "Repairing",
    name: "Charging Problem Repair",
    desc: "Charging port and charging-related problem diagnosis.",
    managedBy: "Anoop",
    icon: Zap,
    badge: "Repair",
    featured: true,
    available: true,
    tags: ["Charging", "Port"],
  },
  {
    id: "s5",
    category: "Repairing",
    name: "Speaker & Mic Repair",
    desc: "Speaker, microphone and audio issue diagnosis.",
    managedBy: "Anoop",
    icon: Volume2,
    badge: "Repair",
    featured: false,
    available: true,
    tags: ["Speaker", "Mic", "Audio"],
  },
  {
    id: "s6",
    category: "Repairing",
    name: "Software Setup & Data Transfer",
    desc: "Phone setup, updates, troubleshooting and data-transfer guidance.",
    managedBy: "Anoop",
    icon: Settings,
    badge: "Service",
    featured: false,
    available: true,
    tags: ["Software", "Setup", "Data"],
  },
  {
    id: "s7",
    category: "Repairing",
    name: "Legal Unlock Assistance",
    desc: "Authorized device assistance with valid ownership or required documents.",
    managedBy: "Anoop",
    icon: LockKeyhole,
    badge: "Documents Required",
    featured: true,
    available: true,
    tags: ["Authorized", "Ownership", "Documents"],
  },
  {
    id: "s8",
    category: "Online Services",
    name: "Aadhaar Services",
    desc: "Aadhaar-related application and correction assistance as supported by the relevant portal.",
    managedBy: "Vikash",
    icon: IdCard,
    badge: "Online",
    featured: true,
    available: true,
    tags: ["Aadhaar", "Correction", "Application"],
  },
  {
    id: "s9",
    category: "Online Services",
    name: "MP Online Services",
    desc: "Citizen services, applications and portal assistance.",
    managedBy: "Vikash",
    icon: Landmark,
    badge: "Popular",
    featured: true,
    available: true,
    tags: ["MP Online", "Application"],
  },
  {
    id: "s10",
    category: "Online Services",
    name: "E-Sam / Online Forms",
    desc: "Form filling, application submission and document upload assistance.",
    managedBy: "Vikash",
    icon: ClipboardList,
    badge: "Online",
    featured: true,
    available: true,
    tags: ["Forms", "Application", "Documents"],
  },
  {
    id: "s11",
    category: "Online Services",
    name: "Government Form Assistance",
    desc: "Assistance with eligible government applications and online forms.",
    managedBy: "Vikash",
    icon: FileText,
    badge: "Online",
    featured: false,
    available: true,
    tags: ["Government", "Forms"],
  },
  {
    id: "s12",
    category: "Banking",
    name: "Airtel Payments Bank Account Opening",
    desc: "Account opening assistance subject to applicable KYC and provider requirements.",
    managedBy: "Vikash",
    icon: CreditCard,
    badge: "Banking",
    featured: true,
    available: true,
    tags: ["Bank Account", "KYC"],
  },
  {
    id: "s13",
    category: "Banking",
    name: "Digital Banking Assistance",
    desc: "Digital banking-related assistance where supported and authorized.",
    managedBy: "Vikash",
    icon: CreditCard,
    badge: "Banking",
    featured: false,
    available: true,
    tags: ["Banking", "Digital"],
  },
  {
    id: "s14",
    category: "Digital",
    name: "Print, Scan & Photocopy",
    desc: "Quick document printing, scanning and photocopy support.",
    managedBy: "Vikash",
    icon: Printer,
    badge: "Quick Service",
    featured: true,
    available: true,
    tags: ["Print", "Scan", "Photocopy"],
  },
  {
    id: "s15",
    category: "Digital",
    name: "Document Upload & Online Help",
    desc: "Digital document preparation and upload assistance.",
    managedBy: "Vikash",
    icon: Upload,
    badge: "Digital",
    featured: false,
    available: true,
    tags: ["Documents", "Upload", "Online"],
  },
  {
    id: "s16",
    category: "Digital",
    name: "Document Scanning",
    desc: "Clear document scanning and digital copy preparation.",
    managedBy: "Vikash",
    icon: ScanLine,
    badge: "Quick Service",
    featured: false,
    available: true,
    tags: ["Scan", "PDF"],
  },
];

export const products = [
  {
    id: "p1",
    category: "Mobile Covers",
    name: "Premium Shockproof Cover",
    model: "Popular Android / iPhone models",
    actualPrice: 199,
    discountPrice: 99,
    rating: 4.8,
    reviewCount: 34,
    stock: true,
    featured: true,
    badge: "Best Seller",
    image:
      "https://images.unsplash.com/photo-1603313011100-34f7f65a801d?auto=format&fit=crop&w=900&q=80",
    description: "Premium shockproof protection with a clean finish.",
    tags: ["Shockproof", "Premium"],
  },
  {
    id: "p2",
    category: "Mobile Covers",
    name: "Clear MagSafe Style Cover",
    model: "Popular iPhone / Android models",
    actualPrice: 599,
    discountPrice: 399,
    rating: 4.7,
    reviewCount: 28,
    stock: true,
    featured: true,
    badge: "Trending",
    image:
      "https://images.unsplash.com/photo-1541877944-ac82a091518a?auto=format&fit=crop&w=900&q=80",
    description: "Clear protective cover with a premium finish.",
    tags: ["Clear", "Protection"],
  },
  {
    id: "p3",
    category: "Mobile Covers",
    name: "Soft Silicone Premium Cover",
    model: "Popular models",
    actualPrice: 449,
    discountPrice: 279,
    rating: 4.6,
    reviewCount: 21,
    stock: true,
    featured: false,
    badge: "Premium",
    image:
      "https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=900&q=80",
    description: "Soft silicone cover with a comfortable grip.",
    tags: ["Silicone", "Soft"],
  },
  {
    id: "p4",
    category: "Mobile Covers",
    name: "Designer Printed Cover",
    model: "Custom / popular models",
    actualPrice: 399,
    discountPrice: 249,
    rating: 4.5,
    reviewCount: 17,
    stock: true,
    featured: false,
    badge: "New",
    image:
      "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=900&q=80",
    description: "Stylish printed cover for everyday protection.",
    tags: ["Designer", "Printed"],
  },
  {
    id: "p5",
    category: "Earphones",
    name: "Wireless Bluetooth Earphones",
    model: "Bluetooth / TWS",
    actualPrice: 1299,
    discountPrice: 799,
    rating: 4.7,
    reviewCount: 42,
    stock: true,
    featured: true,
    badge: "Best Seller",
    image:
      "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=900&q=80",
    description: "Wireless earphones with a compact charging case.",
    tags: ["Wireless", "Bluetooth", "TWS"],
  },
  {
    id: "p6",
    category: "Earphones",
    name: "Everyday Wired Earphones",
    model: "3.5mm / Type-C variants",
    actualPrice: 499,
    discountPrice: 299,
    rating: 4.5,
    reviewCount: 19,
    stock: true,
    featured: false,
    badge: "Value Pick",
    image:
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=80",
    description: "Simple and reliable wired earphones.",
    tags: ["Wired", "3.5mm", "Type-C"],
  },
  {
    id: "p7",
    category: "Earphones",
    name: "Bluetooth Neckband",
    model: "Wireless",
    actualPrice: 999,
    discountPrice: 649,
    rating: 4.6,
    reviewCount: 31,
    stock: true,
    featured: false,
    badge: "Popular",
    image:
      "https://images.unsplash.com/photo-1577174881658-0f30ed549adc?auto=format&fit=crop&w=900&q=80",
    description: "Comfortable wireless neckband for everyday use.",
    tags: ["Neckband", "Wireless"],
  },
  {
    id: "p8",
    category: "Earphones",
    name: "Compact TWS Earbuds",
    model: "Wireless",
    actualPrice: 1499,
    discountPrice: 899,
    rating: 4.7,
    reviewCount: 37,
    stock: true,
    featured: true,
    badge: "Trending",
    image:
      "https://images.unsplash.com/photo-1588423771073-b8903fbb7a1c?auto=format&fit=crop&w=900&q=80",
    description: "Compact TWS earbuds with wireless connectivity.",
    tags: ["TWS", "Wireless"],
  },
  {
    id: "p9",
    category: "Chargers",
    name: "Fast Charging Adapter",
    model: "USB / Type-C",
    actualPrice: 699,
    discountPrice: 449,
    rating: 4.7,
    reviewCount: 29,
    stock: true,
    featured: true,
    badge: "Best Seller",
    image:
      "https://images.unsplash.com/photo-1591290619762-c5881e8c5e3c?auto=format&fit=crop&w=900&q=80",
    description: "Fast charging adapter for compatible devices.",
    tags: ["Fast Charge", "Adapter"],
  },
  {
    id: "p10",
    category: "Chargers",
    name: "Type-C Fast Charge Cable",
    model: "Type-C",
    actualPrice: 399,
    discountPrice: 249,
    rating: 4.6,
    reviewCount: 24,
    stock: true,
    featured: false,
    badge: "Value Pick",
    image:
      "https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=900&q=80",
    description: "Durable Type-C charging and data cable.",
    tags: ["Type-C", "Data Cable"],
  },
  {
    id: "p11",
    category: "Chargers",
    name: "Lightning Charging Cable",
    model: "Lightning",
    actualPrice: 499,
    discountPrice: 299,
    rating: 4.5,
    reviewCount: 18,
    stock: true,
    featured: false,
    badge: "Popular",
    image:
      "https://images.unsplash.com/photo-1615526675159-e248c3021d3f?auto=format&fit=crop&w=900&q=80",
    description: "Reliable Lightning charging cable.",
    tags: ["Lightning", "Charging"],
  },
  {
    id: "p12",
    category: "Chargers",
    name: "Dual Port Car Charger",
    model: "USB / Type-C",
    actualPrice: 799,
    discountPrice: 499,
    rating: 4.5,
    reviewCount: 15,
    stock: true,
    featured: false,
    badge: "Car Accessory",
    image:
      "https://images.unsplash.com/photo-1628815113969-048a2c8f1a2b?auto=format&fit=crop&w=900&q=80",
    description: "Dual-port charging solution for your car.",
    tags: ["Car", "USB"],
  },
  {
    id: "p13",
    category: "Speakers",
    name: "Mini Bluetooth Speaker",
    model: "Portable",
    actualPrice: 1299,
    discountPrice: 799,
    rating: 4.6,
    reviewCount: 26,
    stock: true,
    featured: true,
    badge: "Popular",
    image:
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80",
    description: "Portable Bluetooth speaker with powerful sound.",
    tags: ["Bluetooth", "Portable"],
  },
  {
    id: "p14",
    category: "Power Banks",
    name: "10,000 mAh Power Bank",
    model: "USB / Type-C",
    actualPrice: 1499,
    discountPrice: 999,
    rating: 4.6,
    reviewCount: 23,
    stock: true,
    featured: true,
    badge: "Popular",
    image:
      "https://images.unsplash.com/photo-1609592424851-1f1d8d5d6e11?auto=format&fit=crop&w=900&q=80",
    description: "Portable power bank for convenient charging.",
    tags: ["10000mAh", "Power Bank"],
  },
  {
    id: "p15",
    category: "Protection",
    name: "Tempered Glass",
    model: "Popular models",
    actualPrice: 299,
    discountPrice: 149,
    rating: 4.8,
    reviewCount: 46,
    stock: true,
    featured: true,
    badge: "Best Seller",
    image:
      "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=900&q=80",
    description: "Screen protection glass for supported models.",
    tags: ["Screen Protection"],
  },
  {
    id: "p16",
    category: "Accessories",
    name: "Mobile Holder",
    model: "Desk / Car",
    actualPrice: 399,
    discountPrice: 249,
    rating: 4.5,
    reviewCount: 14,
    stock: true,
    featured: false,
    badge: "Useful",
    image:
      "https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=900&q=80",
    description: "Universal mobile holder for desk and car use.",
    tags: ["Holder", "Desk", "Car"],
  },
];

export const productCategories = [
  "All",
  "Mobile Covers",
  "Earphones",
  "Chargers",
  "Speakers",
  "Power Banks",
  "Protection",
  "Accessories",
];
export const serviceCategories = [
  "All",
  "Repairing",
  "Online Services",
  "Banking",
  "Digital",
];

export const reviews = [
  {
    id: "r1",
    name: "Rahul",
    rating: 5,
    message: "Good service and friendly support.",
    date: "Recent",
  },
  {
    id: "r2",
    name: "Priya",
    rating: 5,
    message: "Quick response for online service work.",
    date: "Recent",
  },
  {
    id: "r3",
    name: "Amit",
    rating: 4,
    message: "Good accessories collection and helpful staff.",
    date: "Recent",
  },
];

export const getDiscountPercentage = (actualPrice, discountPrice) =>
  actualPrice
    ? Math.max(
        0,
        Math.round(((actualPrice - discountPrice) / actualPrice) * 100),
      )
    : 0;
